/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as BookingsNewRouteImport } from './routes/bookings.new'
import { Route as BookingsIdEditRouteImport } from './routes/bookings.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdEditRoute = BookingsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BookingsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/services': typeof ServicesRoute
  '/bookings/$id': typeof BookingsIdRouteWithChildren
  '/bookings/new': typeof BookingsNewRoute
  '/bookings/$id/edit': typeof BookingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/services'
    | '/bookings/$id'
    | '/bookings/new'
    | '/bookings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/services'
    | '/bookings/$id'
    | '/bookings/new'
    | '/bookings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/services'
    | '/bookings/$id'
    | '/bookings/new'
    | '/bookings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  ServicesRoute: typeof ServicesRoute
  BookingsIdRoute: typeof BookingsIdRouteWithChildren
  BookingsNewRoute: typeof BookingsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id/edit': {
      id: '/bookings/$id/edit'
      path: '/edit'
      fullPath: '/bookings/$id/edit'
      preLoaderRoute: typeof BookingsIdEditRouteImport
      parentRoute: typeof BookingsIdRoute
    }
  }
}

interface BookingsIdRouteChildren {
  BookingsIdEditRoute: typeof BookingsIdEditRoute
}

const BookingsIdRouteChildren: BookingsIdRouteChildren = {
  BookingsIdEditRoute: BookingsIdEditRoute,
}

const BookingsIdRouteWithChildren = BookingsIdRoute._addFileChildren(
  BookingsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  ServicesRoute: ServicesRoute,
  BookingsIdRoute: BookingsIdRouteWithChildren,
  BookingsNewRoute: BookingsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
